name: Add Labels to New Issue

on:
  issues:
    types:
      - opened

jobs:
  add_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Labels
        run: |
          go run .github/scripts/add-labels.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
