name: Add Labels to New Issue

on:
  issues:
    types:
      - opened

jobs:
  add_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Labels
        uses: octokit/request-action@v2
        with:
          route: POST /repos/:owner/:repo/issues/:issue_number/labels
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          labels: '["bug", "enhancement"]'  # Add your desired labels here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
