name: DockerBuild

on:
  workflow_call:
    inputs:
      TEST_VAR:
        required: false
        type: string
      PATHS:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: false
  workflow_dispatch:
  
jobs:
  print_env:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    
    steps:
     - name: PrintEnvVars
       run: |
          echo "GITHUB_ACTION: ${{ github.action}}"
          echo "GITHUB_ACTION_PATH: ${{ github.action.path }}"
          echo "TEST_VAR: ${{ inputs.TEST_VAR }}"
          echo "TEST_VAR2: $TEST_VAR2"
          echo "My API_KEY is ${{secrets.TEST_SECRET}}"
                 
     - name: Archive artifacts
       uses: actions/download-artifact@v4
       with:
        name: tenant2_arts

     - name: Check contents
       run: |
          set -x
          pwd
          ls -la $GITHUB_WORKSPACE
          IFS=$'\n' read -d '' -r -a paths <<< "${{ inputs.PATHS }}"
          for path in "${paths[@]}"
          do
            cat "tenant2_arts/$path"
          done
          set +x
       
