name: Docker Build

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      TEST_VAR:
        required: false
        type: string
jobs:
  print_env:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.TEST_VAR }}
      TEST_VAR: ${{ inputs.TEST_VAR }}
      TEST_VAR2: ${{ vars.TEST_VAR2 }}
    steps:
     - name: PrintEnvVars
       run: |
          echo "GITHUB_ACTION: ${{ github.action}}"
          echo "GITHUB_ACTION_PATH: ${{ github.action.path }}"
          echo "TEST_VAR: $TEST_VAR"
          echo "TEST_SECRET: $TEST_SECRET"
          echo "TEST_VAR2: $TEST_VAR2"
          
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"
       
     - name: Dump job context
       env:
          JOB_CONTEXT: ${{ toJson(job) }}
       run: echo "$JOB_CONTEXT"  
       
  prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Build Go Application
        run: |
          go mod tidy
          go build -o main .
              
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.imageName }}:latest .

