name: Docker Build

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string

jobs:
  print_env:
    runs-on: ubuntu-latest
    steps:
     - name: Build Go Application
       run: |
          echo "GITHUB_ACTION_PATH: ${{ GITHUB_ACTION_PATH }}"
           
  prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Build Go Application
        run: |
          go mod tidy
          go build -o main .
              
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.imageName }}:latest .

