name: Docker Build

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Build Go Application
        run: |
          go mod tidy
          go build -o main .
          run: |


      
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.imageName }}:latest .

  Trigger-Build-in-Tenant2:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/avinash221988/tenant2/actions/workflows/workflow2.yaml/dispatches" \
            -d '{"ref":"main"}'
