name: Prerequisites
on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
  workflow_run:
    workflows: [DockerBuild]
    types: [completed]
jobs:
  prerequisites:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Build Go Application
        run: |
          go mod tidy
          go build -o main .
              
      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.imageName }}:latest .

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow DockerBUild failed'
